# Generated by Django 5.2.8 on 2025-12-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_export_grades', 'Can export grades'), ('can_approve_enrollment', 'Can approve enrollment'), ('can_manage_schedule', 'Can manage schedule'), ('can_view_reports', 'Can view reports')]},
        ),
    ]
