# Generated by Django 5.2.8 on 2026-01-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportdata',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='passport/selfie/'),
        ),
    ]
