# Generated by Django 4.2.28 on 2026-02-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passportdata_birth_place_passportdata_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_embedding',
            field=models.JSONField(blank=True, help_text='Face embedding vector for verification', null=True),
        ),
    ]
