# Generated by Django 5.2.8 on 2026-06-14 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('materials', '0004_material_current_version_material_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('live', 'Live Session'), ('video', 'Video Lesson')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_lessons', to='materials.material'),
        ),
    ]
