# Generated by Django 5.2.8 on 2026-01-11 14:10

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Subject = apps.get_model("subjects", "Subject")
    Direction = apps.get_model("directions", "Direction")
    default_direction = Direction.objects.first()
    if default_direction is None:
        default_direction = Direction.objects.create(name="Umumiy", language="uz", degree="bachelor")
    through = Subject.directions.through
    for subject in Subject.objects.all():
        if getattr(subject, "direction_id", None):
            continue
        direction_id = (
            through.objects.filter(subject_id=subject.id)
            .values_list("direction_id", flat=True)
            .first()
        )
        subject.direction_id = direction_id or default_direction.id
        subject.save(update_fields=["direction"])


def backwards(apps, schema_editor):
    Subject = apps.get_model("subjects", "Subject")
    through = Subject.directions.through
    for subject in Subject.objects.exclude(direction_id__isnull=True):
        through.objects.get_or_create(subject_id=subject.id, direction_id=subject.direction_id)


class Migration(migrations.Migration):

    dependencies = [
        ("directions", "0001_initial"),
        ("subjects", "0002_remove_subject_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="direction",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="directions.direction"),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="subject",
            name="directions",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="code",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject_type",
        ),
        migrations.AlterField(
            model_name="subject",
            name="direction",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="directions.direction"),
        ),
    ]
