# Generated by Codex on 2026-01-11

from django.db import migrations, models


def forwards(apps, schema_editor):
    Subject = apps.get_model("subjects", "Subject")
    through = Subject.directions.through
    for subject in Subject.objects.all():
        direction_id = getattr(subject, "direction_id", None)
        if direction_id:
            through.objects.get_or_create(subject_id=subject.id, direction_id=direction_id)


def backwards(apps, schema_editor):
    Subject = apps.get_model("subjects", "Subject")
    for subject in Subject.objects.all():
        direction_id = subject.directions.values_list("id", flat=True).first()
        if direction_id:
            subject.direction_id = direction_id
            subject.save(update_fields=["direction"])


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0003_subject_direction_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="directions",
            field=models.ManyToManyField(related_name="subjects", to="directions.direction"),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="subject",
            name="direction",
        ),
    ]
