# Generated by Codex on 2026-01-12

from django.db import migrations


def forwards(apps, schema_editor):
    Subject = apps.get_model("subjects", "Subject")
    Direction = apps.get_model("directions", "Direction")
    through = Subject.directions.through

    table_names = schema_editor.connection.introspection.table_names()
    if through._meta.db_table not in table_names:
        schema_editor.create_model(through)

    default_direction = Direction.objects.first()
    if default_direction:
        for subject in Subject.objects.all():
            if not through.objects.filter(subject_id=subject.id).exists():
                through.objects.create(subject_id=subject.id, direction_id=default_direction.id)


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0004_subject_directions"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
