# Generated by Django 5.2.8 on 2026-01-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_timetable_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='semester',
        ),
    ]
