# Generated by Django 5.2.8 on 2026-01-11 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0001_initial'),
        ('subjects', '0002_remove_subject_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradebookentry',
            unique_together={('student', 'subject')},
        ),
        migrations.RemoveField(
            model_name='gradebookentry',
            name='semester',
        ),
    ]
