# Generated by Django 5.2.8 on 2026-01-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0002_alter_gradebookentry_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gradebookentry",
            name="attendance_score",
        ),
    ]
