# Generated by Django 5.2.8 on 2026-01-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0003_remove_gradebookentry_attendance_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradebookentry',
            name='final_score',
        ),
    ]
