# Generated by Django 5.2.8 on 2025-12-18 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_tests', '0001_initial'),
        ('tests_app', '0002_alter_question_options_remove_test_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttest',
            old_name='correct_answers',
            new_name='current_question_index',
        ),
        migrations.RenameField(
            model_name='studenttest',
            old_name='score',
            new_name='score_percent',
        ),
        migrations.AlterUniqueTogether(
            name='studenttest',
            unique_together={('student', 'test')},
        ),
        migrations.AddField(
            model_name='studenttest',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answered_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_app.option'),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('student_test', 'question')},
        ),
        migrations.RemoveField(
            model_name='studenttest',
            name='total_questions',
        ),
    ]
