# Generated by Django 5.2.8 on 2026-03-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_tests', '0002_rename_correct_answers_studenttest_current_question_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='face_verified_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='rejected_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
