# Generated by Django 5.2.8 on 2026-01-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='program',
        ),
    ]
