# Generated by Django 5.2.8 on 2026-01-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
