# Generated by Django 5.2.8 on 2026-01-07 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_language_alter_group_name'),
        ('semesters', '0002_semestersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='semester',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='semesters.semester'),
        ),
    ]
