# Generated by Django 5.2.8 on 2026-01-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='semester',
        ),
    ]
