# Generated by Django 5.2.8 on 2026-01-11 14:25

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0006_remove_group_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="group",
            name="year",
        ),
    ]
