# Generated by Django 5.2.8 on 2026-01-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_normalize_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalrecord',
            name='attendance',
            field=models.CharField(choices=[('present', 'Bor'), ('absent', 'Yoq')], default='present', max_length=20),
        ),
    ]
