# Generated by Django 5.2.8 on 2026-01-07 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='semesters.semester')),
            ],
        ),
    ]
