# Generated by Django 5.2.8 on 2025-12-18 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_program'),
        ('subjects', '0001_initial'),
        ('tests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='test',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='test',
            name='teacher_subject',
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='groups.group'),
        ),
        migrations.AddField(
            model_name='test',
            name='pass_score',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
