# Generated by Django 5.2.8 on 2026-01-11 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('tests_app', '0002_alter_question_options_remove_test_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='lessons.lesson'),
        ),
    ]
