# Generated by Django 5.2.8 on 2026-01-16 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0003_test_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='pass_score',
        ),
        migrations.AddField(
            model_name='test',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
