# Generated by Django 5.2.8 on 2026-01-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='semester',
        ),
    ]
