# Generated by Django 5.2.8 on 2026-01-13 10:20

from django.db import migrations


def normalize_attendance_status(apps, schema_editor):
    Attendance = apps.get_model("attendance", "Attendance")
    Attendance.objects.filter(status="late").update(status="present")


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(normalize_attendance_status, migrations.RunPython.noop),
    ]
