# Generated by Django 5.2.8 on 2026-03-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='face_check_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_success_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_verified_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
