# Generated by Django 5.2.8 on 2026-03-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_face_check_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='joined_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='joined_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
