# Generated by Django 5.2.8 on 2026-06-14 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_manual_override_attendance_overridden_at_and_more'),
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_opened', models.BooleanField(default=False)),
                ('material_viewed', models.BooleanField(default=False)),
                ('material_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('test_score', models.FloatField(default=0.0)),
                ('test_attended', models.BooleanField(default=False)),
                ('assignment_submitted', models.BooleanField(default=False)),
                ('total_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Faol qatnashdi'), ('partial', 'Qisman qatnashdi'), ('absent', 'Qatnashmadi')], default='absent', max_length=10)),
                ('lesson_opened_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='lessons.lesson')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
