# Generated by Django 5.2.8 on 2026-06-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_add_lesson_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonactivitylog',
            name='video_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonactivitylog',
            name='video_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonactivitylog',
            name='video_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonactivitylog',
            name='video_progress_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lessonactivitylog',
            name='video_watch_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
