# Generated by Django 5.2.8 on 2026-01-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_remove_applicant_program_choice_and_more'),
        ('groups', '0003_remove_group_program'),
        ('profiles', '0002_remove_studentprofile_program_and_more'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
