# Generated by Django 5.2.8 on 2025-12-19 10:00

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, upload_to=assignments.models.submission_file_path),
        ),
    ]
