# Generated by Django 5.2.8 on 2026-01-11 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_submission_file'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='lessons.lesson'),
        ),
    ]
