# Generated by Django 4.2.28 on 2026-02-05 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live', '0004_live_stage_ptt_hand'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVerificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_enabled', models.BooleanField(default=True)),
                ('verification_interval', models.IntegerField(default=5, help_text='Verification interval in seconds')),
                ('confidence_threshold', models.FloatField(default=0.7, help_text='Minimum confidence for verification')),
                ('max_faces_allowed', models.IntegerField(default=1, help_text='Maximum faces allowed in frame')),
                ('auto_attendance', models.BooleanField(default=True, help_text='Automatically mark attendance on verification')),
                ('alert_on_multiple_faces', models.BooleanField(default=True)),
                ('alert_on_no_face', models.BooleanField(default=True)),
                ('alert_on_verification_fail', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Face Verification Settings',
                'verbose_name_plural': 'Face Verification Settings',
            },
        ),
        migrations.CreateModel(
            name='LiveFaceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_embedding', models.JSONField(blank=True, help_text='Face embedding from enrollment/profile', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('verified', 'Verified'), ('failed', 'Failed'), ('ended', 'Ended')], default='active', max_length=20)),
                ('last_verification_at', models.DateTimeField(blank=True, null=True)),
                ('verification_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_sessions', to='live.liveparticipant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_sessions', to='live.liveroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('participant', 'room')},
            },
        ),
        migrations.CreateModel(
            name='LiveFaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('verification', 'Verification'), ('multiple_faces', 'Multiple Faces Detected'), ('no_face', 'No Face Detected'), ('low_confidence', 'Low Confidence'), ('success', 'Verification Success'), ('failure', 'Verification Failure')], max_length=30)),
                ('faces_detected', models.IntegerField(default=0)),
                ('confidence', models.FloatField(blank=True, help_text='Verification confidence score', null=True)),
                ('frame_embedding', models.JSONField(blank=True, help_text='Embedding from current frame', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('alert_sent', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_events', to='live.liveroom')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='live.livefacesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room', '-created_at'], name='live_livefa_room_id_c30c5f_idx'), models.Index(fields=['user', '-created_at'], name='live_livefa_user_id_e9733b_idx'), models.Index(fields=['session', '-created_at'], name='live_livefa_session_91a374_idx')],
            },
        ),
    ]
