# Generated by Django 5.2.8 on 2026-03-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_faceverificationsettings_livefacesession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceverificationsettings',
            name='confidence_threshold',
            field=models.FloatField(default=0.8, help_text='Minimum confidence for verification (cosine mapped to [0,1]; 0.80 ≈ raw cosine 0.60)'),
        ),
    ]
