# Generated by Django 5.2.8 on 2026-03-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_alter_faceverificationsettings_confidence_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveparticipant',
            name='accumulated_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
