# Generated by Django 5.2.8 on 2026-03-14 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0007_liveparticipant_accumulated_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveparticipant',
            name='last_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
