# Generated by Django 5.2.8 on 2026-03-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0008_liveparticipant_last_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livefaceevent',
            name='event_type',
            field=models.CharField(choices=[('success', 'Verification Success'), ('low_confidence', 'Low Confidence'), ('multiple_faces', 'Multiple Faces Detected'), ('no_face', 'No Face Detected'), ('no_reference', 'No Reference Embedding'), ('no_embedding', 'No Frame Embedding'), ('invalid_frame', 'Invalid Frame'), ('ai_error', 'AI Service Error'), ('disabled', 'Verification Disabled'), ('error', 'General Error'), ('failure', 'Verification Failure')], max_length=30),
        ),
    ]
