# Generated by Django 5.2.8 on 2026-01-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('proctoring', '0001_initial'),
        ('student_tests', '0002_rename_correct_answers_studenttest_current_question_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorsession',
            name='student_test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctor_session', to='student_tests.studenttest'),
        ),
        migrations.AlterField(
            model_name='proctorsession',
            name='exam_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctor_session', to='assessment.examattempt'),
        ),
    ]
