# Generated by Django 5.2.8 on 2026-01-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0002_proctorsession_student_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorsession',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proctorsession',
            name='blocked_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proctorsession',
            name='last_present_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proctorsession',
            name='missing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
