# Generated by Django 5.2.8 on 2026-03-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0003_proctorsession_blocked_proctorsession_blocked_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorsession',
            name='success_checks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proctorsession',
            name='total_checks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
