# Generated by Django 5.2.8 on 2025-12-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_presence', models.BooleanField(default=True)),
                ('enable_face_match', models.BooleanField(default=True)),
                ('presence_threshold', models.FloatField(default=0.6)),
                ('face_match_threshold', models.FloatField(default=0.7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Settings',
                'verbose_name_plural': 'AI Settings',
            },
        ),
    ]
