# Generated by Django 5.2.8 on 2026-01-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='proctor_missing_seconds',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='proctor_strict',
            field=models.BooleanField(default=True),
        ),
    ]
