# Generated by Codex on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_aisettings_proctor_missing_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisettings",
            name="ai_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="api_base_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="timeout_seconds",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="retry_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="ocr_confidence_threshold",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="max_image_size_mb",
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="face_model",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="detection_backend",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="enforce_detection",
            field=models.BooleanField(default=False),
        ),
    ]
