# Generated by Django 5.2.8 on 2026-03-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aisettings_extended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
