# Generated by Django 5.2.8 on 2026-01-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_studentprofile_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='workload',
        ),
    ]
