# Generated by Django 5.2.8 on 2026-01-11 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_group_level_replace_year'),
        ('materials', '0003_material_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='current_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='materials', to='groups.group'),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF File'), ('video', 'Video'), ('audio', 'Audio'), ('ppt', 'PowerPoint'), ('doc', 'Word Document'), ('image', 'Image'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MaterialResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('resource_type', models.CharField(choices=[('file', 'File'), ('link', 'Link'), ('video', 'Video')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/resources/')),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='materials.material')),
            ],
        ),
    ]
