# Generated by Django 5.2.8 on 2026-01-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_remove_applicant_program_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='passport_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
