# Generated by Django 5.2.8 on 2026-01-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_alter_applicant_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationwindow',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='registrationwindow',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='registrationwindow',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='registrationwindow',
            name='start_at',
        ),
    ]
