# Generated by Django 5.2.8 on 2026-01-31 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_applicant_birth_place_applicant_card_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['-created_at']},
        ),
    ]
