# Generated by Codex
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0007_alter_applicantdocument_passport_back"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="user",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="applicant_profile", to="accounts.user"),
        ),
    ]
